### ISSUE TITLE
MathJax CDN is shutting down.

### ISSUE THREAD

**Issue by david-briggs-tq** [kyso-io/react-jupyter#1]
Hello, it appears that the MathJax CDN is shutting down.

```
WARNING: cdn.mathjax.org has been retired. Check https://www.mathjax.org/cdn-shutting-down/ for migration tips.
```

I'm not familiar enough with other popular CDN services to submit a PR to fix the issue. The offending line can be found here:

https://github.com/eoinmurray/react-jupyter/blob/master/src/index.js#L11

Thank you,

david@tranquant.com

**Comment by MartinKolarik** [comment]
You should be able to fix this easily by switching to https://www.jsdelivr.com/package/npm/mathjax

**Comment by eoinmurray** [comment]
Sorry for missing this for so long! 

If someone wants to make a pull request for this - I'm happy to accept it.
