### ISSUE TITLE
SEC: XSS Vulnerability

### ISSUE THREAD

**Issue by MikeShi42** [kyso-io/react-jupyter#3]
I notice that this package has the ability to insert script tags for javascript content in a ipynb. I was wondering if there was a danger of introducing XSS attacks. I tried to verify this myself but it seems like the JS code never executes even though the script tag with the arbitrary JS code is included.

It would be nice if there was an option to disable rendering of JS to prevent XSS vulnerabilities.

**Comment by MikeShi42** [comment]
Was able to probe further and show that it's possible to execute arbitrary JS. Similar behavior is seen on https://nbviewer.jupyter.org. However, github seems to have a method of sanitization to scrub out any script components, even if they're in HTML.

**Comment by eoinmurray** [comment]
hmmm... I'll look into this.
